version: '3'

services:
  server:
    container_name: hoa-resident
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    ports:
    #      - 8080:80
    labels:
      - traefik.enable=true
      - traefik.http.services.hoa-resident.loadbalancer.server.port=80
      - traefik.http.routers.hoa-resident.rule=Host("hoa.innque.com")
      - traefik.http.routers.hoa-resident.entrypoints=web
      - traefik.http.routers.hoa-resident_secured.rule=Host("hoa.innque.com")
      - traefik.http.routers.hoa-resident_secured.entrypoints=websecure
      - traefik.http.routers.hoa-resident_secured.tls.certresolver=myhttpchallenge
      - traefik.http.routers.hoa-resident.middlewares=redirect@file


networks:
  default:
    external:
      name: proxy-server-network
